spring:
  security:
    user:
      name: policyadmin
      password: zb!XztG34
  http:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:mariadb://mariadb:3306/policyadmin
    driverClassName: org.mariadb.jdbc.Driver
    username: policy_user
    password: policy_user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.onap.policy.common.spring.utils.CustomImplicitNamingStrategy

server:
  port: 6969
  ssl:
    enabled: false

pap:
  name: PapGroup
  aaf: false
  pdpParameters:
    heartBeatMs: 120000
    updateParameters:
      maxRetryCount: 1
      maxWaitMs: 30000
    stateChangeParameters:
      maxRetryCount: 1
      maxWaitMs: 30000
  topicParameterGroup:
    topicSources:
    - topic: POLICY-PDP-PAP
      servers:
      - message-router
      topicCommInfrastructure: dmaap
      fetchTimeout: 15000
    - topic: POLICY-HEARTBEAT
      effectiveTopic: POLICY-PDP-PAP
      consumerGroup: policy-pap
      servers:
      - message-router
      topicCommInfrastructure: dmaap
      fetchTimeout: 15000
    topicSinks:
    - topic: POLICY-PDP-PAP
      servers:
      - message-router
      topicCommInfrastructure: dmaap
    - topic: POLICY-NOTIFICATION
      servers:
      - message-router
      topicCommInfrastructure: dmaap
  healthCheckRestClientParameters:
  - clientName: api
    hostname: policy-api
    port: 6969
    userName: policyadmin
    password: zb!XztG34
    useHttps: true
    basePath: policy/api/v1/healthcheck
  - clientName: distribution
    hostname: policy-distribution
    port: 6969
    userName: healthcheck
    password: zb!XztG34
    useHttps: true
    basePath: healthcheck
  - clientName: dmaap
    hostname: message-router
    port: 3905
    useHttps: true
    basePath: topics

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
      path-mapping.prometheus: metrics
