DROP TABLE IF EXISTS PdpEntity
DROP TABLE IF EXISTS PdpGroupEntity
DROP TABLE IF EXISTS PolicyEntity
DROP TABLE IF EXISTS PolicySetEntity
DROP TABLE IF EXISTS PolicySetToPolicyEntity
DROP TABLE IF EXISTS DatabaseLockEntity
