spring:
  security:
    user:
      name: policyadmin
      password: zb!XztG34
  datasource:
    url: jdbc:postgresql://postgres:5432/policyadmin
    driverClassName: org.postgresql.Driver
    username: policy_user
    password: policy_user
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.onap.policy.common.spring.utils.CustomImplicitNamingStrategy
  mvc:
    converters:
      preferred-json-mapper: gson

server:
  port: 6969
  servlet:
    context-path: /policy/pap/v1
  ssl:
    enabled: false

pap:
  name: PapGroup
  topic:
    pdp-pap.name: POLICY-PDP-PAP
    notification.name: POLICY-NOTIFICATION
    heartbeat.name: POLICY-HEARTBEAT
  pdpParameters:
    heartBeatMs: 120000
    updateParameters:
      maxRetryCount: 1
      maxWaitMs: 30000
    stateChangeParameters:
      maxRetryCount: 1
      maxWaitMs: 30000
  topicParameterGroup:
    topicSources:
      - topic: ${pap.topic.pdp-pap.name}
        servers:
          - noop
        topicCommInfrastructure: noop
        useHttps: false
        fetchTimeout: 15000
      - topic: ${pap.topic.heartbeat.name}
        effectiveTopic: ${pap.topic.pdp-pap.name}
        consumerGroup: policy-pap
        servers:
          - noop
        topicCommInfrastructure: noop
        useHttps: false
        fetchTimeout: 15000
    topicSinks:
      - topic: ${pap.topic.pdp-pap.name}
        servers:
          - noop
        topicCommInfrastructure: noop
        useHttps: false
      - topic: ${pap.topic.notification.name}
        servers:
          - noop
        topicCommInfrastructure: noop
        useHttps: false
  healthCheckRestClientParameters:
  - clientName: api
    hostname: policy-api
    port: 6969
    userName: policyadmin
    password: zb!XztG34
    useHttps: false
    basePath: policy/api/v1/healthcheck

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
      path-mapping:
        -metrics: plain-metrics
        -prometheus: metrics
